// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcBet.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bet.Migrations
{
    [DbContext(typeof(MvcBetContext))]
    partial class MvcBetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bet.Models.BetViewModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("FirstTeame")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("coefficent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("gameResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("whoWin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Bets");
                });
#pragma warning restore 612, 618
        }
    }
}
